# Generated by Django 3.0.6 on 2020-05-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=100)),
                ('uploader_email', models.EmailField(max_length=100)),
                ('dataset_time', models.DateTimeField(auto_now=True)),
                ('dataset_type', models.CharField(choices=[('flowers_dataset', 'flowers_dataset'), ('UNM_dataset', 'UNM_dataset'), ('NEU_dataset', 'NEU_dataset'), ('Dartmouth_dataset', 'Dartmouth_dataset')], max_length=100)),
                ('dataset_file', models.FileField(upload_to='raw-datasets/%Y/%m/%d/')),
            ],
        ),
    ]
