# Generated by Django 3.0.7 on 2020-11-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='dataset_type',
            field=models.CharField(choices=[('flowers_dataset', 'flowers_dataset'), ('UNM_dataset', 'UNM_dataset'), ('NEU_dataset', 'NEU_dataset'), ('csv_only', 'csv_only'), ('NEU_dataset_covars', 'NEU_dataset_covars'), ('Dartmouth_dataset', 'Dartmouth_dataset')], max_length=100),
        ),
    ]
